name: hrdigitech
description: "Zomato App Clone by HR DigiTech"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get:
  sizer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/AppIcon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/AppIcon.png"
  min_sdk_android: 21
  remove_alpha_ios: true